#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build calculator app"
  lane :build_calculator do
    scan(
      project: "TurboCalculator.xcodeproj",
      scheme: "TurboCalculator",
      clean: true,
      build_for_testing: true,
      derived_data_path: "DerivedData"
    )
  end

  desc "Run tests of calculator app"
  lane :test_app do |options|
    scan(
      project: "TurboCalculator.xcodeproj",
      scheme: "TurboCalculator",
      derived_data_path: "DerivedData",
      output_directory: "Report",
      device: options[:device],
      app_identifier: "QAGuru.Calculator",
      reinstall_app: true,
      test_without_building: true,
      result_bundle: true,
      testplan: options[:testplan]
    )
  end
end
