name: iOS UI-tests

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      testplan:
        required: true
        default: 'Debug'
        type: choice
        options:
          - Debug
          - Regress
          - Smoke
      device:
        required: true
        default: 'iPhone 13'
        type: choice
        options:
          - 'iPhone 13'
          - 'iPhone 14'
          - 'iPhone 15'
          - 'iPhone 15 Pro'

env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  TESTPLAN: ${{ inputs.testplan || 'Debug' }}
  DEVICE: ${{ inputs.device || 'iPhone 14' }}
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_ENDPOINT: https://allure.autotests.cloud/
  ALLURE_PROJECT_ID: 3978
  ALLURE_RESULTS: allure-results

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos

    steps:
      - name: Checkout git
        uses: actions/checkout@v3
      - name: Get info
        run: env
      - name: Clean old files
        run: |
          rm -rf ./DerivedData
          rm -rf ./Report
          rm -rf xcresults
      - name: Setup env
        run: |
          ruby -v
          bundle install
      - name: Build app
        run: fastlane ios build_calculator
      - name: Run tests
        run: fastlane ios test_app testplan:"${TESTPLAN}" device:"${DEVICE}"
      - name: Install xcresults
        if: ${{ always()}}
        run: |
          curl -OL https://github.com/eroshenkoam/xcresults/releases/latest/download/xcresults
          chmod +x xcresults
      - name: Convert to allure results
        if: ${{ always()}}
        run: |
          ./xcresults export ./Report/TurboCalculator.xcresult ./allure-results
      - name: Save allure results
        if: ${{ always()}}
        uses: actions/upload-artifact@v4.1.0
        with:
          name: Allure
          path: allure-results
          retention-days: 30

  report:
    name: Send report to TestOPS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download allure results
        uses: actions/download-artifact@v4
        with:
          name: Allure
          path: allure-results   

      - name: Upload allure-results to Allure TestOPS
        uses: simple-elf/allurectl-action@master
        id: allure-ee
        with:
          allure_results: $ALLURE_RESULTS
          allure_ee_endpoint: $ALLURE_ENDPOINT
          allure_ee_token: $ALLURE_TOKEN
          project_id: $ALLURE_PROJECT_ID
