name: iOS starter workflow

on:
  workflow_dispath

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos

    steps:
      - name: Checkout git
        uses: actions/checkout@v3
      - name: Setup env
        run: env
      - name: Build app
        run: pwd
      - name: Run tests
        run: pwd
        
