name: iOS UI-tests

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      testplan:
        required: true
        default: 'Debug'
        type: choice
        options:
          - Debug
          - Regress
          - Smoke
      device:
        required: true
        default: 'iPhone 13'
        type: choice
        options:
          - 'iPhone 13'
          - 'iPhone 14'
          - 'iPhone 15'
          - 'iPhone 15 Pro'

env:
  LC_ALL: 'en_US.UTF-8'
  LANG: 'en_US.UTF-8'
  LANGUAGE: 'en_US.UTF-8'
  TESTPLAN: ${{ inputs.testplan || 'Debug' }}
  DEVICE: ${{ inputs.device || 'iPhone 14' }}

jobs:
  build:
    name: Build and Test Calculator App
    runs-on: macos

    steps:
      - name: Checkout git
        uses: actions/checkout@v4
        
      - name: Get Environment Info
        run: env
        working-directory: ${{ github.workspace }}

      - name: Clean Cache Files
        run: |
          rm -rf ./DerivedData
          rm -rf ./Report
          rm -rf ./allure-results
          rm -rf xcresults
          rm -rf allurectl

      - name: Install Ruby dependencies
        run: bundle install

      - name: Build app
        run: fastlane ios build_calculator

      - name: Run UI-tests
        run: fastlane ios test_app testplan:"${TESTPLAN}" device:'${DEVICE}'

      - name: Install xcresults
        if: ${{ always()}}
        run: |
          curl -OL https://github.com/eroshenkoam/xcresults/releases/latest/download/xcresults
          chmod +x xcresults

      - name: Convert xcresult to allure-results
        if: ${{ always()}}
        run: |
          ./xcresults export ./Report/TurboCalculator.xcresult ./allure-results

      - name: Save allure-results
        if: ${{ always()}}
        uses: actions/upload-artifact@v4.1.0
        with:
          name: Allure
          path: allure-results
          retention-days: 15

      - name: Download allurectl (macos-arm)
        if: ${{ always()}}
        run: |
          curl -L https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_darwin_arm64 -o allurectl
          chmod +x allurectl

      - name: Upload Results to TestOPS
        if: ${{ always()}}
        env:
          LAUNCH_NAME: "Launch ${GITHUB_RUN_NUMBER} from ${GITHUB_REPOSITORY}"
        run: |
          ./allurectl upload \
            --endpoint https://allure.autotests.cloud/ \
            --token ${{ secrets.ALLURE_TOKEN }} \
            --project-id 3978 \
            --launch-name "${LAUNCH_NAME}"" \
            allure-results
