name: iOS UI-tests

on:
  workflow_dispatch:
    inputs:
      testplan:
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - regress
          - smoke

env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos

    steps:
      - name: Checkout git
        uses: actions/checkout@v3
      - name: Get info
        run: env
      - name: Clean old files
        run: |
          rm -rf ./DerivedData
          rm -rf ./Report
      - name: Setup env
        run: |
          ruby -v
          bundle install
      - name: Build app
        run: fastlane ios build_app
      - name: Run tests
        run: fastlane ios test_app
        
